### PR TITLE
[F005] Created Login and Register pages

### PR DESCRIPTION
**Pull request by grigorem**

### CODE REVIEW

**Review by SusanLuebke — COMMENTED** [review]
Very neatly organized. Looks good overall. We'll need to discuss consistency across buttons, etc.

**Review by SusanLuebke — COMMENTED** [review]
Looks good by me.

**Review by SusanLuebke — APPROVED** [review]
n/a

**Comment by grigorem** [comment]
[[F005] Create Login and Registration page](https://trello.com/c/KgUospkB/35-f005-create-login-and-registration-page)

**Pull request merged**
