### PR TITLE
[F004] First Pull request

### PR DESCRIPTION
**Pull request by SusanLuebke**

### CODE REVIEW

**Review by jinirun — CHANGES_REQUESTED** [review]
Could you please give a link to the login page? Everything else looks great. Ready to be merged.

**Comment by SusanLuebke** [comment]
DO NOT MERGE - I made the change Jini requested and now the entire page is randomly overlapping.

**Comment by SusanLuebke** [comment]
A potential github carfuffle in that it did a partial merge of the two, creating a mess. Kim was able to revert back to the working version and all is now fine. Not considered an average fix. Ready to be reveiwed again.

**Review by jinirun — APPROVED** [review]
Looks good. Ready to be merged.

**Pull request merged**
